# Site Settings
title: "Windows 12 Wiki"
description: ""
remote_theme: pages-themes/primer # This ensures your theme stays active

# Markdown Configuration
kramdown:
  # This tells Jekyll to treat HTML blocks as real HTML, not text
  parse_block_html: true
  syntax_highlighter: rouge
  autolink: true
  commonmark:
    hard_wrap: false

defaults:
  - scope:
      path: "" # empty string means all files in the project
      type: "pages"
    values:
      layout: "default"
      
footer_text: "GitBook 镜像"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-optional-front-matter

# Build Settings
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .github/workflows
