name: Build and Deploy mdBook
on:
  workflow_run:
    workflows: ["Format Code"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Build mdBook Into Subpath
        run: |
          mdbook build -d ./_site/docs 
          # Matches the folder name you want in your URL (e.g., ://domain.com)

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Combined Staging Directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
